### ISSUE TITLE
Unable to process objects with "-" inside of object name

### ISSUE THREAD

**Issue by MicAlter31** [365businessdev/vscode-alxmldocumentation#11]
Hi!
I found a bug when creating a xml doc definition for a function which uses a record which table names contains a "-" inside.

Sample:
```
   /// <summary> 
    /// This is the function summary.
    /// </summary>
    /// <param name="Param1">Specifies a Text parameter.</param>
    /// <param name="MyRecord">Specifies an instance of type of record.</param>
    /// <param name="AnotherRecord">Specifies an instance of type of record.</param>
    /// <param name="ErrorMessage">This variable contains an error message if the process failed.</param>
    /// <returns>**true** if the function was successfully processed. Otherwise it will be **false** and the parameter **ErrorMessage** will give information why the process failed.</returns>
    procedure CallFunction(Param1: Text; MyRecord: record MyRecord; var AnotherRecord: Record "Another - Record"; var ErrorMessage: Text): Boolean;
    begin
    end;

```

The created markdown will split the record "Another - Record" at the '-' character and creates a further parameter defintion.

Output:
`Warnings:
============= CallFunction(Param1: Text; MyRecord: record MyRecord; var AnotherRecord: Record "Another - Record"; var ErrorMessage: Text) [Cod50000.SampleCodeunit.al:292] =============
Parameter 'Record' description missing!
The XML comment has a param tag for 'ErrorMessage', but there is no parameter with that name.`

**Comment by sirhc101** [comment]
Fixed in version 0.3.2
