### ISSUE TITLE
Documentation and var parameters 

### ISSUE THREAD

**Issue by msomp** [365businessdev/vscode-alxmldocumentation#18]
First of all thank you for the interesting extension for the documentation of methods in BC. I think that makes a lot of sense and am considering using this type of source code documentation in my apps.
During my first tests I noticed that the transfer of var parameters into the .md file might not work properly, see screenshot (Parameter 'var PerCompanyUpgradeTags' description missing!)

In addition, I would have liked to use the workspace folder as markdown_path, such as:
"settings": {
"bdev-al-xml-doc.markdown_path": "${workspaceFolder}\\Doc"
}
Is that possible?

![Bildschirmfoto 2020-07-23 um 13 36 54](https://user-images.githubusercontent.com/55102386/88283202-411caa80-cceb-11ea-9de2-c4ff34f92b5d.jpg)
Best regards from Vienna, Martin.

**Comment by 365businessdev** [comment]
Hello Martin,

thank you for your feedback. We will take a look into the issue you reported. Looks like a bug.

Regarding your request for `${workspaceFolder}` placeholder: That's a really good idea. We will implement this in the next version.

**Comment by sirhc101** [comment]
Hello @msomp,

The requested feature regarding the `${workspaceFolder}` is already there... at least similar to what you've asked for.
If you do not configure the `markdown_path` in configuration or if you leave it blank `"bdev-al-xml-doc.markdown_path": ""` the export will automatically use the current workspace folder and append  `doc` to it.

Does this solve your request?

Thank you.
Chris

**Comment by msomp** [comment]
Hi Chris,

thank you for your response. My concern was originally to have only one doc-directory in the workspace on the same level as the App- and the Test directory. With this I wanted to ensure that the documentation of the main and the test app ended up in the same directory. I could have entered the directory directly in the settings, but thought that a placeholder would be better. But now I think I will probably not document the test app in this way, so the current version would be ok for me.

But now I have encountered another problem, namely that the configuration at the directory level cannot be set differently. I want to activate the extension for one directory, but not for the other (App - yes, Test - no). Is this probably a multi-root workspace issue?

**Comment by sirhc101** [comment]
Hi Martin,

yes you're right! Thank you for reporting.
In current version all configurations will be only queried from the top-level in multi-root workspaces. This is a bug! I also found it recently while developing and testing the new feature for issue #19.

I'm currently working on it.

**Comment by msomp** [comment]
Great, very well done. Thanks.
