### ISSUE TITLE
Default value : checkProcedureDocumentation = false

### ISSUE THREAD

**Issue by fvet** [365businessdev/vscode-alxmldocumentation#19]
Would it be possible to set the default value of checkProcedureDocumentation to false?
We've 35+ repo's, in combination with 40+ workspaces and this results in 30.000+ warnings about missing documentation.

I know we can update the settings.json and code-workspace settings with checkProcedureDocumentation : false, but it would be fine if the extension by default would disable the check.

**Comment by sirhc101** [comment]
Hello fvet, 

Thank you for your feedback. 

We discussed this internally and decided to not disable the feature by default.
But we will add an additional option you can set. This option will asks everytime you open a new workspace if you want to enable or disable the feature. The selection will then be written to the workspace settings.json, so this question only appears once per workspace.

I hope this is fine for you, but we personally do not like the approach to disable the complete feature by default. Our personal experience is that if you need to enable something to make sure your code will be checked (e.g. CodeCop) often this not happen.

**Comment by sirhc101** [comment]
We've added the following implementation and will release it with the 0.4.2 version coming out soon.

In `settings.json` (I would prefer the user settings) add the following entry:
```
{
    "bdev-al-xml-doc.askEnableCheckProcedureDocumentation": true
}
```

From now, if you open a new workspace the following question appears:
![image](https://user-images.githubusercontent.com/39621236/88388502-eea7c080-cdb4-11ea-8b74-f69ac5e5ad7c.png)

As a result of this answer the `checkProcedureDocumentation` setting will be created in the Workspace `settings.json`.
```
{
    "bdev-al-xml-doc.checkProcedureDocumentation": true
}
```
