### ISSUE TITLE
Only global procedures will be exported

### ISSUE THREAD

**Issue by 365businessdev** [365businessdev/vscode-alxmldocumentation#2]
Only global procedures are recognized on cmd "Generate markdown documentation[...]". Local/Internal...etc are skipped.

Original reported from [rating by Christian Ziepel](https://marketplace.visualstudio.com/items?itemName=365businessdevelopment.bdev-al-xml-doc&ssr=false#review-details)

**Comment by 365businessdev** [comment]
This behaviour is currently by design. We had planned to export only visible and global procedures, since the original reason for the extension was to document the source code for dependent extensions in AL.

We will consider adding a configuration setting.

**Comment by MAC-Christian** [comment]
From this perspective it makes totally sense, only to export globals. 
It would be nice to have it configurable. We want to use the markdown result in azure devops as internal wiki. (see screenshot attached). Therefore we need also local/internal procedures :)
![2020-06-15_10h58_00](https://user-images.githubusercontent.com/40752996/84638760-aebd0600-aef7-11ea-91f2-0053e83e3364.png)

**Comment by 365businessdev** [comment]
@MAC-Christian Thank you, we understand. 
We are working on a configuration setting to enable export for local and internal procedures.

**Comment by 365businessdev** [comment]
We've added a new configuration parameter `exportScope` with version 0.2.1
![image](https://user-images.githubusercontent.com/63005008/84689509-5e6a9600-af41-11ea-9992-97c3c033c845.png)
