### ISSUE TITLE
Shows warning even when the function is documented

### ISSUE THREAD

**Issue by Entreri86** [365businessdev/vscode-alxmldocumentation#20]
First of all, thank you, thank you very much for the work done :-)

It only happens in some functions (strange), that the documentation is set for all the parameters and shows a warning that it is not documented in the VsCode output.

![image](https://user-images.githubusercontent.com/15688332/88366287-12551180-cd89-11ea-9bc2-434cef10136c.png)

I have tried to look for a pattern but I have not been able to see what may be happening.

![image](https://user-images.githubusercontent.com/15688332/88366377-4af4eb00-cd89-11ea-89eb-028256169375.png)

If you need any type of data, I will be happy to provide it. I use the latest version of Vscode and Al-Language.

¡Many thanks in advance!

**Comment by sirhc101** [comment]
Thank you very much for reporting. 
I checked this and found the issue in one of the regex. Fixed it in dev branch already.

**Comment by Entreri86** [comment]
¡Thanks!
