### ISSUE TITLE
Reserved word and method name in double quotes 

### ISSUE THREAD

**Issue by msomp** [365businessdev/vscode-alxmldocumentation#21]
Hello again,

I noticed that if, for example, the word trigger appears in the summary, the method name is no longer correctly formed in the documentation.

Also method names in double quotes are not recognized, like 
procedure "APProcID Cr.Memo" (): Integer

**Comment by sirhc101** [comment]
Fixed with version 0.4.2

**Comment by msomp** [comment]
Thank you!
These things are now working.
