### ISSUE TITLE
Strange .md filename

### ISSUE THREAD

**Issue by msomp** [365businessdev/vscode-alxmldocumentation#24]
Hello,
it looks like special codings are leading to some kind of confused md. file naming.
The filename produced with the attached al-file for example is: "and not rec.IsTemporary() then.md".

[N2SEventsTest.Codeunit.al.zip](https://github.com/365businessdev/vscode-alxmldocumentation/files/4993675/N2SEventsTest.Codeunit.al.zip)

Thanks again.

**Comment by sirhc101** [comment]
Thanks again!! Next beer at TechDays is on me :wink:

I'm currently testing the fix for this issue.

**Comment by sirhc101** [comment]
Fixed with version 0.4.4

**Comment by msomp** [comment]
Thank you, that fix seems to be working. Very well done! There are other topics that I think may be improved, but I'm going on vacation soon, so if you want I give you more feedback again afterwards.
