### ISSUE TITLE
Typo in DOC0001 Message

### ISSUE THREAD

**Issue by rvanbekkum** [365businessdev/vscode-alxmldocumentation#26]
Dear @365businessdev team,
I've noticed there is a typo in the message from code-analyzer rule DOC0001.
![image](https://user-images.githubusercontent.com/7383241/89770803-90dade80-daff-11ea-8395-46d773fe9157.png)
I think the text should be "The procedure MyProcedure **is** missing documentation." (or something similar).

**Comment by sirhc101** [comment]
Oops! You're absolutly right. Will fix it with next release.
