### ISSUE TITLE
Option for no code-analyzer message for procedures in objects with Access=Internal

### ISSUE THREAD

**Issue by rvanbekkum** [365businessdev/vscode-alxmldocumentation#28]
Dear @365businessdev team,
Would it be possible to have an option that makes it so that the code-analyzer does not report missing documentation for procedures in objects with Access=Internal (or even more restricted)?
With `bdev-al-xml-doc.procedureTypes` we can already set the type of procedures that will be checked, but if you have a global/public procedure in an internal codeunit, then the code-analyzer will still report that the documentation is missing for that procedure.

**Comment by sirhc101** [comment]
We're pretty unhappy the way we implemented the `procedureTypes` configuration at the moment and currently designing a new way to configure the diagnostics and procedure helper (tooltip, documentation insert, etc.)

I put this one our requirement list for the new implementation!

Thank you.

**Comment by rvanbekkum** [comment]
Hi @365businessdev,
How can we configure that if a public procedure is in an `Access = Internal` object, that it does not need documentation?

Example:
![example public procedure in internal object](https://user-images.githubusercontent.com/7383241/100443364-da006f80-30a9-11eb-929f-8b9f40dc05b1.png)

Settings used are:
```
    "al-xml-doc.CheckProcedureDocumentationForAccessLevel": [
        "Protected", "Public"
    ],
    "al-xml-doc.CheckProcedureDocumentationForType": [
        "Global Procedures",
        "Protected Procedures"
    ],
```
(I believe CheckProcedureDocumentationForAccessLevel is only for the markdown generation though)

In this case I would like to have the code analyzer to not report "missing documentation" for this procedure.

**Comment by sirhc101** [comment]
Closed. Please see #40
