### ISSUE TITLE
Documentation code-fix also available on problems with different ID

### ISSUE THREAD

**Issue by rvanbekkum** [365businessdev/vscode-alxmldocumentation#29]
Dear @365businessdev,
I noticed that the code-fix "Add documentation" is also available for code-analyzer warnings with different IDs.

Here is a sample with a procedure without documentation and with a record type `MyRecord` that does _not_ exist:
```pascal
procedure MyProcedure(MyRec: Record "MyRecord")
begin
end;
```
If you go down to Problems and open up the code-fixes for the error AL0185 "Table 'MyRecord' is missing", then the "Add documentation" code-fix is available for this error:
![image](https://user-images.githubusercontent.com/7383241/90620416-b1e3b380-e212-11ea-9824-0523bb47ba74.png)
I think it should only be suggested when you select the error with ID DOC0001.

Just a minor issue, but maybe you could have a look?

**Comment by sirhc101** [comment]
Thank you for reporting. That's pretty weird! The Code Actions are already assigned to the Diagnostic Codes. I've debugged your example and everything seems correctly...but in frontend I see the same behaviour!
