### ISSUE TITLE
Code analysis rule for parameter documentation cannot find parameter if object name contains parentheses

### ISSUE THREAD

**Issue by rvanbekkum** [365businessdev/vscode-alxmldocumentation#32]
Dear @365businessdev team,
The following example raises an issue with code analysis rule `AL-XML-DOC(DOC0010)`:
```pascal
    /// <summary>
    /// This is my documentation.
    /// </summary>
    /// <param name="MyExample">Parameter documentation</param>
    procedure MyProcedure(MyExample: Record "Item Charge Assignment (Sales)")
    var
        myInt: Integer;
    begin

    end;
```
![parentheses_issue](https://user-images.githubusercontent.com/7383241/94907837-09776f00-04a1-11eb-9933-9202530c495e.png)
The subtype of the parameter contains parentheses, and as a result, the code analysis rule cannot find the parameter correctly.

**Comment by sirhc101** [comment]
Hello @rvanbekkum, you're right. Our RegEx do not support parentheses inside object or params. Thank you for reporting. Added this to our test collection.
