### ISSUE TITLE
Code analysis rule for documentation not working if parentheses are not on the same line

### ISSUE THREAD

**Issue by rvanbekkum** [365businessdev/vscode-alxmldocumentation#33]
Dear @365businessdev team,
Through this issue I would like to report the following issue. If you have a procedure and the parentheses are not on the same line, then the code analysis rule that checks for documentation is not working correctly.
Example:
```pascal
    procedure MyProcedure(
        MyExample: Record Customer
    )
    var
        myInt: Integer;
    begin

    end;
```
(N.B. I did not add documentation for the procedure, so we would expect an info message from the code analysis rule, but it does not show up)

I know you are working on refactoring the extension, and still overall the current version works pretty well, but I am reporting this, so that you could maybe take these scenarios into account 😄.

**Comment by sirhc101** [comment]
Thank you @rvanbekkum. I've added this scenario into our test collection for the upcoming version.
