### ISSUE TITLE
Code analysis rules are also applied on .dal files that are not in the current project

### ISSUE THREAD

**Issue by rvanbekkum** [365businessdev/vscode-alxmldocumentation#35]
Dear @365businessdev,
I noticed that there are also messages coming from the extension for .dal files:
![dal-al-xml-doc-info-messages](https://user-images.githubusercontent.com/7383241/96984722-d3b62b00-1520-11eb-8b79-12067dd17146.png)
I don't think that is intentional or necessary, right? Not sure whether something could and/or should be done to change this, but at the very least it confused me for a moment 😉.

**Comment by 365businessdev** [comment]
Thank you for reporting. We'll fix this bug in our upcoming release.
