### ISSUE TITLE
Cannot run Generate markdown documentation

### ISSUE THREAD

**Issue by chris-amco** [365businessdev/vscode-alxmldocumentation#39]
When I try to run "AL DOC: Generate markdown documentation" / "AL DOC: Generate markdown documentation for directory", I receive the following error messages:

"Command 'AL DOC: Generate markdown documentation' resulted in an error (Running the contributed command: 'al-xml-doc.exportMarkdown' failed.)"

"Unable to find Visual Studio Code extension. Please try re-install."

- I have set "Documentation Export Path".
- VS Code details
  Version: 1.51.1 (user setup)
  Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
  Date: 2020-11-10T23:34:32.027Z
  Electron: 9.3.3
  Chrome: 83.0.4103.122
  Node.js: 12.14.1
  V8: 8.3.110.13-electron.0
  OS: Windows_NT x64 10.0.19041
- AL Language extension : 6.1.362735
- AL XML Documentation : 1.0.0. I have tried uninstalling and reinstalling the extension, but it did not help. I am able to use the extension to create XML comments in my source code.

Any suggestions?

Thanks & regards,
Chris

p.s. Thank you for making this tool. It looks like the kind of thing I am looking for, as I would like to prototype in AL and then generate documentation based on the source code.

**Comment by sirhc101** [comment]
Hello Chris,

Thank you very much for reporting.
As we have described in the readme file, we are currently in the process of reimplementing the transcription export. To be honest, we haven't really tested the export functionality as we just left it as it was in the previous version.

But you're right, that's a bug. I already fixed it and provided a minor update (v1.0.1) in Visual Studio marketplace. 
Please update to this version. The export should work again.

Just to mention: Please be aware, that we're currently not supporting inherit documentations in markdown export. This kind of documentations will be warned by the markdown creation. Just pls ignore for the moment. We're already working on it.
