### ISSUE TITLE
<returns> tag contents are missing from generated markdown

### ISSUE THREAD

**Issue by chris-amco** [365businessdev/vscode-alxmldocumentation#41]
Hello,
I am not sure if I have missed something, but in the generated markdown for all of my procedures, the <returns> tag contents are missing from the generated markdown (it says the return value is "None"). 
I have tried with and without the "verbose" setting switched on. Is there anything else that I need to set?
Thanks in advance,
Chris

AL XML documentation v1.0.3.

Example XML comment
`   /// <summary>
    /// GetCashIn : To initialise "Transfer In" page on mobile
    /// </summary>
    /// <param name="p_gBatchNo">Batch No. returned by NewBatch(), code[20]].</param>
    /// <returns>Return variable p_gJSONText of type text.</returns>
`
 
Generated markdown
# GetCashIn Method
GetCashIn : To initialise "Transfer In" page on mobile

## Syntax
```javascript
GetCashIn(p_gBatchNo: code[20])
```

### *"p_gBatchNo"*
Type: code[20]<br/>
Batch No. returned by NewBatch(), code[20]].

**Comment by sirhc101** [comment]
Hi @chris-amco 

Thank you very much for reporting. This looks like a bug for me.
We are currently working on a new version of markdown export to support `<inheritdoc/>` documentations and custom stylesheets. I will add this test case.

/Chris

**Comment by chris-amco** [comment]
Hi Chris Thanks for the reply. In case you are interested, here are a couple of other issues that I have been having:When I split a procedure’s signature over more than 1 line, no markdown is generated for that procedure (despite it having XML comments). This is easy to work-around, just put the whole signature on a single line.I want to generate markdown for public procedures only. I have set the following :     "al-xml-doc.CheckProcedureDocumentationForAccessLevel": [        "Public"    ],    "al-xml-doc.CheckProcedureDocumentationForType": [        "Global Procedures"    ],And I have not added XML comments to my private procedures. However, when I generate the markdown, the private procedures are included. I am not sure what else I need to set to avoid this. Looking forward to the new version!Chris From: Christoph KriegSent: 02 December 2020 14:46To: 365businessdev/vscode-alxmldocumentationCc: chris-amco; MentionSubject: Re: [365businessdev/vscode-alxmldocumentation] <returns> tag contents are missing from generated markdown (#41) Hi @chris-amcoThank you very much for reporting. This looks like a bug for me.We are currently working on a new version of markdown export to support <inheritdoc/> documentations and custom stylesheets. I will add this test case./Chris—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
