### ISSUE TITLE
"Inherit AL XML Documentation Comment" results in 'badly formed XML' if parameter type object name contains spaces (and therefore surrounded by quotes in the signature)

### ISSUE THREAD

**Issue by rvanbekkum** [365businessdev/vscode-alxmldocumentation#43]
Dear @365businessdev,
If you use the command "Inherit AL XML Documentation Comment" the parameter types are added in the reference to the original procedure in the interface.
If a parameter type is an object with a name that needs to be surrounded by quotes, e.g. `"Temp Blob"`, then this results in a warning message:
![bad XML](https://user-images.githubusercontent.com/7383241/102067424-5b226b00-3dfb-11eb-8df1-9acc5ea5434d.png)
Also, hovering over the procedure does not give the documentation in this case.
Could you look into this?

**Comment by rvanbekkum** [comment]
Perhaps you could escape the quotes with `&quot;`?

**Comment by sirhc101** [comment]
Sorry for the delay in fixing your supported issue!
We have recently released the version 1.0.5 which fixed this issue.
