### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by BobBrownCAI** [365businessdev/vscode-alxmldocumentation#44]
- Issue Type: `Performance`
- Extension Name: `bdev-al-xml-doc`
- Extension Version: `1.0.4`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\bobb.CAI\AppData\Local\Temp\365businessdevelopment.bdev-al-xml-doc-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sirhc101** [comment]
@BobBrownCAI Thank you for reporting. Could you pls add the cpuprofile to this issue, so I can investigate a little bit more?
