### ISSUE TITLE
[QUESTION] Is It possible to run this extension also on OSX

### ISSUE THREAD

**Issue by elweilando** [365businessdev/vscode-alxmldocumentation#46]
Is It possible to run this extension also on OSX?

**Comment by 365businessdev** [comment]
Hello @elweilando,

we did not tested it to be honest, but we will do so and come back to you.

**Comment by sirhc101** [comment]
Hello @elweilando,

Sorry for waiting.
We've now tested the upcoming version 1.1.0 on OSX and can confirm that AL XML Documentation extension working fine.
