### ISSUE TITLE
Documentation Export Path Setting don't work as expected

### ISSUE THREAD

**Issue by elweilando** [365businessdev/vscode-alxmldocumentation#47]
If I define an export path in settings, every path starts from base path `C:\Program Files\Microsoft VS Code\`.
If I leave this setting empty, then a directory "docs" in app-root will be created.
Expectation is, that the directory I define in export settings should be relative from app-root.

**Comment by sirhc101** [comment]
Hello @elweilando,

you can use `${workspaceFolder}` as a placeholder in the `DocumentationExportPath` setting.

We described this in the documentation as well:
> **Note**<br>`DocumentationExportPath` does support `${workspaceFolder}` as an placeholder.<br><br>_Example_<br>`"al-xml-doc.DocumentationExportPath": "${workspaceFolder}/documentations/src/"`

Hope that helps.

/Chris
