### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by TCMatthiasMartin** [365businessdev/vscode-alxmldocumentation#52]
This tool is really cool, but if you're working on a vertical solution with a few big files it slows the development really down.

For example, try to create a new Posting routing, just copy the Sales Post Codeunit and try to work in it.
This Codeunit got over 9500 lines it takes around 2 Minutes to save changes if the AL XML Documentation is enabled.
If you disable this extension it takes around 1 sek.

In 8 of 10 times it's faster to save, cancel the process, close VSCode and restart it, than waiting for the process to end.

If you need help to create an environment to get this issue just write me.
Perhaps it's possible to optimize this extension.

**Comment by sirhc101** [comment]
Thank you @TCMatthiasMartin for reporting.

We did some performance enhancements in the upcoming version, but I will look into it and try find out whats taking that much time in saving document.

**Comment by sirhc101** [comment]
You're absolutely right, we've two performance issues here.
First, the procedure detection takes way to long:
![image](https://user-images.githubusercontent.com/39621236/113581361-56dac180-9627-11eb-967d-3d2e6a1f7cbd.png)

Second, the process is fired each time you change anything in the file. So If you for example do type 4 characters the update process is exectued 4 times and we do not wait 5 seconds, but 20 seconds. 

To be honest our files are much smaller than for example Sales Post Codeunit, but it is a bug that we will fix as soon as possible. 
Thanks again for bringing this issue to our attention.

**Comment by TCMatthiasMartin** [comment]
@sirhc101 normally we have smaller files too, but in a few cases the files are (in my opinion) way to large.

I'm happy that I could help you to find an issues.
Thanks for reacting that fast to my request! 

Thumbs up!
