### ISSUE TITLE
Won't generate Markdown for particular file

### ISSUE THREAD

**Issue by horribleCodes** [365businessdev/vscode-alxmldocumentation#54]
In my module all but one AL-documents can successfully generate a corresponding Markdown file. When I attempt to create the .md for one of the page extensions, the extension will create a subfolder for the document and print in the output log that 0 errors occured, but the subfolder will always be empty. In fact, if there is an existing file (any file) in the folder when executing the cmdlet, it will get deleted. There are other page extensions with almost identical commentary that don't show any problems, the only discernible difference is that this is an extension of a role center.
Here is the entire code of the page extension in question.
```al
/// <summary>
/// Extends Page 9022
/// </summary>
/// <remarks>
/// Adds an Action Group containing links to the pages My Session and Sessions.
/// 
/// - My Session (Page 73610)
/// - Sessions (Page 73611)
/// </remarks>
pageextension 73610 "Business Manager RC CKN" extends "Business Manager Role Center"
{
    actions
    {
        addafter(SetupAndExtensions)
        {
            group("Sessions CKN")
            {
                Caption = 'Sessions';
                action("My Session CKN")
                {
                    ApplicationArea = All;
                    Caption = 'My Session';
                    RunObject = page "My Session CKN";
                }
                action("Active Sessions CKN")
                {
                    ApplicationArea = All;
                    Caption = 'Sessions';
                    RunObject = page "Sessions CKN";
                }
            }
        }
    }
}
```

**Comment by sirhc101** [comment]
Thank you again, for reporting this issue. I tested it in the upcoming version:

![image](https://user-images.githubusercontent.com/39621236/114727643-ab282480-9d3e-11eb-9ba8-f85e873aca62.png)
