### ISSUE TITLE
Description in IntelliSense

### ISSUE THREAD

**Issue by 365businessdev** [365businessdev/vscode-alxmldocumentation#7]
Add parameter (`<param>`) information to IntelliSense
![image](https://user-images.githubusercontent.com/63005008/86354831-06829d80-bc6a-11ea-9eb4-e0b89942ad81.png)

**Comment by sirhc101** [comment]
Will not be added due to announced feature in Business Central 2020 Release Wave 2

https://docs.microsoft.com/en-us/dynamics365-release-plan/2020wave2/smb/dynamics365-business-central/code-documentation-comments
