### ISSUE TITLE
Unable to set language for procedure examples

### ISSUE THREAD

**Issue by virusbear** [365businessdev/vscode-alxmldocumentation#72]
In [PR 69](https://github.com/365businessdev/vscode-alxmldocumentation/pull/69) I added the language parameter when exporting the example block for AL Object.
Unfortunately this does not work for procedures yet. 
Also the `code` property of the `documentation.example` object is `undefined`.
[PR 71](https://github.com/365businessdev/vscode-alxmldocumentation/pull/71) aims at fixing both of those issues.

**Comment by sirhc101** [comment]
PR merged in Version 1.1.7
