### ISSUE TITLE
Disable warnings for ControlAddins

### ISSUE THREAD

**Issue by fvet** [365businessdev/vscode-alxmldocumentation#77]
@sirhc101 Would it be possible to provide a fix for this issue, or should we wait for the new version? Any ETA on when the new release would be available?

We've configured our workspace with following settings

```
"al-xml-doc.CheckObjectDocumentationInformationLevel": "Disabled",
    "al-xml-doc.CheckProcedureDocumentationInformationLevel": "Warning",
    "al-xml-doc.CheckProcedureDocumentationForType": [
        "Global Procedures"
    ]
```
However, I can't get rid of the warnings (neither via #pragma) that are shown on the events for our controladdin objects. Any idea on how to disable these?

![image](https://user-images.githubusercontent.com/25268332/158620462-704a660a-c9e3-423d-9002-a51ca73aa1b3.png)

![image](https://user-images.githubusercontent.com/25268332/158621264-c08f3928-84e2-4d8e-ac13-8d9af861a7b7.png)

**Comment by sirhc101** [comment]
Hi @fvet 

Sure, that's a small change. I will provide a fix for this asap.

Regarding your question for the new version. The base version is completed, but we're currently testing a lot to make sure performance is good. Right now I'm not very happy with the performance of big files, but we've some ideas how to solve the problems.

**Comment by sirhc101** [comment]
You can now specify two new options in `CheckProcedureDocumentationForType`:

- `Control Add-In Events`
- `Control Add-In Procedures`

Additionally procedures in control add-ins will no longer be recognized as global, local or internal procedure. All are now handled with `Control Add-In Procedures` instead

![image](https://user-images.githubusercontent.com/39621236/158633721-705ce3ba-3f02-4917-8d11-5a3ab21d0222.png)

Version 1.1.7 is on it's way to marketplace

**Comment by fvet** [comment]
Just installed the latest version and it works fine!

Thanks a lot for the quick fix ;)
