### ISSUE TITLE
Generate XML Documentation can be triggered from a line inside a procedure above another procedure

### ISSUE THREAD

**Issue by rvanbekkum** [365businessdev/vscode-alxmldocumentation#8]
Dear @365businessdev,
First off, thank you for the extension.

I've noticed that you can trigger the documentation-generator typing `///` in a line in the file above a procedure, e.g.:
![triggeredEverywhere](https://user-images.githubusercontent.com/7383241/86586213-d4ce4700-bf87-11ea-83ea-0f7c8e319831.gif)

Could you look into this?

**Comment by 365businessdev** [comment]
Thank you for reporting this issue. We will fix with the next release

**Comment by sirhc101** [comment]
Fixed in version 0.3.1
