### ISSUE TITLE
Setting to enable/disable XML documentation comments generator

### ISSUE THREAD

**Issue by rvanbekkum** [365businessdev/vscode-alxmldocumentation#9]
Dear @365businessdev,
The [AL Code Outline](https://github.com/anzwdev/al-code-outline) extension offers a similar feature for generating documentation comments, which can be disabled through a setting `alOutline.docCommentsType`.
Could you add a setting that allows us to disable documentation comments to be created after typing `///` from this extension? This way we can choose one of the two implementations.

**Comment by sirhc101** [comment]
New setting `enableDocComments` in version 0.3.1
